### ISSUE TITLE
Allow for data types

### ISSUE THREAD

**Issue by viable-hartman** [bojanbjelic/xml2json#5]
This project is great, but only generates quoted output when sometimes we also want doubles, integers, etc.  I propose figuring out how to load an XSD for type checking during the transform.  The below is really simple, but worked for my needs 👍 

Modify xml2json as follows:

`    
    <xsl:variable name="xsd" select="document('YOUR_SCHEMA.xsd')"/>`

`<xsl:template match="*" mode="detect">
...
            <xsl:when test="count(./child::*) = 0">
                
                <xsl:variable name="pName" select="name(..)" />
                <xsl:variable name="eltName" select="local-name()" />
                <xsl:variable name="optionType" select="$xsd//xs:element[@name = $pName]//xs:element[@name = $eltName]/@type" />
                
                <xsl:choose>
                    <xsl:when test="$optionType = 'xs:double' or $optionType = 'xs:int'">
                        <xsl:text>"</xsl:text><xsl:value-of select="name()"/>" : <xsl:apply-templates select="."/>
                    </xsl:when>
                    <xsl:otherwise>
                        <xsl:text>"</xsl:text><xsl:value-of select="name()"/>" : "<xsl:apply-templates select="."/><xsl:text>"</xsl:text>
                    </xsl:otherwise>
                </xsl:choose>
                <xsl:if test="count(following-sibling::*) &gt; 0">, </xsl:if>
            </xsl:when>
        </xsl:choose>
    </xsl:template>
...
`

This is a basic idea, but in this way you can output typed data too.

**Comment by bojanbjelic** [comment]
@viable-hartman thanks for the suggestion - an option to have in mind.
I don't have a lot of time to dedicate to this TBH - feel free to fork or submit a pull request.
